name: adithya-anytype
base: core24
version: __SNAP_VERSION__
title: Anytype (Unofficial)
contact: https://github.com/Adithya-Rajendran/anytype-snap
issues: https://github.com/Adithya-Rajendran/anytype-snap/issues
license: Proprietary
icon: snap/gui/icon.png
summary: Unofficial Anytype client
website: https://anytype.io
source-code: https://github.com/Adithya-Rajendran/anytype-snap
description: |
  Local-first, peer-to-peer knowledge OS.

  This is an UNOFFICIAL build.

  - Upstream Source: https://github.com/anyproto/anytype-ts
  - Snap Build Source: https://github.com/Adithya-Rajendran/anytype-snap

  Built from source using Anytype Heart (Go) and Anytype TS (Electron).
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  adithya-anytype:
    command: anytype --no-sandbox
    desktop: usr/share/applications/adithya-anytype.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - network
      - network-bind
      - password-manager-service
      - home
      - system-observe
      - mount-observe
      - browser-support

parts:
  anytype-heart:
    plugin: go
    source: https://github.com/anyproto/anytype-heart.git
    source-type: git
    source-tag: __HEART_VERSION__
    source-depth: 1
    build-snaps:
      - go/1.24/stable
      - node/24/stable
    build-packages:
      - libprotoc-dev
      - protobuf-compiler
    override-build: |
      # TRICK: Create the directory the Makefile expects to find
      # We go up one level (..) because the build runs inside a subfolder
      mkdir -p ../anytype-ts/dist/lib

      make install-dev-js

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/anytype-artifacts

      cp -r ../anytype-ts/dist/* $SNAPCRAFT_PART_INSTALL/opt/anytype-artifacts/

  anytype-ts:
    plugin: npm
    source: https://github.com/anyproto/anytype-ts.git
    source-type: git
    source-tag: __TS_VERSION__
    source-depth: 1
    build-snaps:
      - go/1.24/stable
      - node/24/stable
    after: [anytype-heart]
    build-packages:
      - libsecret-1-dev
      - jq
      - pkg-config
      - python3
      - python3-setuptools
      - build-essential
      - libssl-dev
      - libsecret-1-dev
    stage-packages:
      - libsecret-1-0
    override-build: |
      # Added to remove the default check for the protocol. This does not work for my snap package. If someone knows how to fix this please help.
      sed -i 's/app.setAsDefaultProtocolClient/console.log/g' electron.js

      npm install --save-dev webpack-cli --legacy-peer-deps
      npm run update:locale
      npm run build:deps

      ./update.sh ubuntu-latest $CRAFT_ARCH_BUILD_FOR

      cp -r $SNAPCRAFT_STAGE/opt/anytype-artifacts/* dist/

      npm run dist:linux -- --linux --dir

      cp -r dist/linux-unpacked/* $CRAFT_PART_INSTALL/

      # Create the standard applications directory
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications/

      # Renaming it to 'adithya-anytype.desktop' avoids conflicts with other sources
      cp anytype.desktop $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop

      # Point it to the icon located in snap/gui/icon.png (which lands in meta/gui/)
      sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|' $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop

      # Update the Exec to launch the snap. We have to do this because this is an unofficial snap.
      sed -i 's|^Exec=.*|Exec=adithya-anytype %U|' $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop
