name: adithya-anytype
base: core24
version: 0.54.2
title: Anytype (Unofficial)
contact: https://github.com/Adithya-Rajendran/anytype-snap
issues: https://github.com/Adithya-Rajendran/anytype-snap/issues
license: Proprietary
icon: snap/gui/icon.png
summary: Unofficial Anytype client
website: https://anytype.io
source-code: https://github.com/Adithya-Rajendran/anytype-snap
description: |
  Local-first, peer-to-peer knowledge OS.

  This is an UNOFFICIAL build.

  - Upstream Source: https://github.com/anyproto/anytype-ts
  - Snap Build Source: https://github.com/Adithya-Rajendran/anytype-snap

  Built from source using Anytype Heart (Go) and Anytype TS (Electron).
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  adithya-anytype:
    command: anytype --no-sandbox
    desktop: usr/share/applications/adithya-anytype.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - network
      - network-bind
      - password-manager-service
      - home
      - system-observe
      - mount-observe
      - browser-support

parts:
  anytype-heart:
    plugin: go
    source: https://github.com/anyproto/anytype-heart.git
    source-type: git
    source-tag: v0.48.1
    source-depth: 1
    build-snaps:
      - go/1.24/stable
      - node/24/stable
    build-packages:
      - libprotoc-dev
      - protobuf-compiler
      - make
      - musl-tools
    override-build: |
      # Set up Go environment variables (mirrors "Setup GO" step)
      export GOPATH=$(go env GOPATH)
      export GOBIN=$(go env GOPATH)/bin
      export PATH=$PATH:$GOBIN:$(pwd)/deps

      # Set version flags
      GIT_SUMMARY=$(git describe --tags --always 2>/dev/null || echo "v0.48.1")
      export FLAGS="-X github.com/anyproto/anytype-heart/util/vcs.GitSummary=${GIT_SUMMARY}"
      export BUILD_TAG_NETWORK=envproduction

      go mod download

      make setup-protoc
      make setup-go
      # skip setup-gomobile — not needed for Linux server binary

      # Patch musl cross-compilers to use native gcc on Ubuntu
      sed -i 's/x86_64-linux-musl-gcc/gcc/g' makefiles/ci-cross-compile-library.mk
      sed -i 's/aarch64-linux-musl-gcc/gcc/g' makefiles/ci-cross-compile-library.mk
      sed -i 's/-static //g' makefiles/ci-cross-compile-library.mk
      sed -i 's/-extldflags=-static//g' makefiles/ci-cross-compile-library.mk

      make cross-compile-library-linux-$CRAFT_ARCH_BUILD_FOR

      make protos-js
      make ci-js-protos

      mkdir -p .tarball
      cp linux-$CRAFT_ARCH_BUILD_FOR .tarball/grpc-server
      chmod +x .tarball/grpc-server
      cp -r protobuf  .tarball/protobuf
      cp -r json      .tarball/json
      # relations/ doesn't exist in v0.48.1, skip it

      tar -czf anytype-heart.tar.gz -C .tarball .

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/anytype-artifacts
      cp anytype-heart.tar.gz $SNAPCRAFT_PART_INSTALL/opt/anytype-artifacts/anytype-heart.tar.gz

  anytype-ts:
    plugin: npm
    source: https://github.com/anyproto/anytype-ts.git
    source-type: git
    source-tag: v0.54.2
    source-depth: 1
    build-snaps:
      - go/1.24/stable
      - node/24/stable
    after: [anytype-heart]
    build-packages:
      - libsecret-1-dev
      - jq
      - pkg-config
      - python3
      - python3-setuptools
      - build-essential
      - libssl-dev
    stage-packages:
      - libsecret-1-0
    override-build: |
      # Added to remove the default check for the protocol. This does not work for my snap package. If someone knows how to fix this please help.
      sed -i 's/app.setAsDefaultProtocolClient/console.log/g' electron.js

      npm install --include=dev --legacy-peer-deps
      npm install --include=dev webpack webpack-cli --legacy-peer-deps

      cp $CRAFT_STAGE/opt/anytype-artifacts/anytype-heart.tar.gz .

      tar -zxf anytype-heart.tar.gz
      mv -fv grpc-server "dist/anytypeHelper"

      rm -rf dist/lib/pb
      rm -rf dist/lib/pkg
      rm -rf dist/lib/protos
      rm -rf dist/lib/json/generated/*.json

      mv -fv protobuf/* "dist/lib/"
      mkdir -p dist/lib/json/generated
      mv -fv json/* "dist/lib/json/generated"
      rm -rf protobuf
      rm -rf relations
      rm -rf json
      rm -f anytype-heart.tar.gz

      npm run update:locale
      npm run dist:linux -- --linux --dir

      cp -r dist/linux-unpacked/* $CRAFT_PART_INSTALL/

      # Create the standard applications directory
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications/

      # Renaming it to 'adithya-anytype.desktop' avoids conflicts with other sources
      cp anytype.desktop $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop

      # Point it to the icon located in snap/gui/icon.png (which lands in meta/gui/)
      sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|' $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop

      # Update the Exec to launch the snap. We have to do this because this is an unofficial snap.
      sed -i 's|^Exec=.*|Exec=adithya-anytype %U|' $CRAFT_PART_INSTALL/usr/share/applications/adithya-anytype.desktop
